name: Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "Manual Release Tag"
        required: true
        default: "v0.3.3"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name || github.event.inputs.tag || 'main' }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build arm64 binary
        run: |
          make clean
          make all ARCH=arm64
          mv airdrop airdrop_arm64

      - name: Build x86_64 binary
        run: |
          make clean
          make all ARCH=x86_64
          mv airdrop airdrop_x86_64

      - name: Create universal binary
        run: |
          lipo -create -output airdrop airdrop_arm64 airdrop_x86_64
          rm -f airdrop_arm64 airdrop_x86_64

      - name: Package for Homebrew
        run: tar -czf airdrop_darwin_universal.tar.gz airdrop

      - name: Get SHA256
        id: sha
        run: |
          SHA256=$(shasum -a 256 airdrop_darwin_universal.tar.gz | cut -d " " -f 1)
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT

      - name: Update Homebrew formula
        run: |
          VERSION="${{ github.event.inputs.tag || github.ref_name }}"
          VERSION_STRIPPED=${VERSION#v}

          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/xvoland/homebrew-tap.git
          cd homebrew-tap

          sed -i '' "s|url \".*\"|url \"https://github.com/xvoland/airdrop/releases/download/${VERSION}/airdrop_darwin_universal.tar.gz\"|" Formula/airdrop.rb
          sed -i '' "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha256 }}\"|" Formula/airdrop.rb
          sed -i '' "s|version \".*\"|version \"${VERSION_STRIPPED}\"|" Formula/airdrop.rb

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update airdrop formula to ${VERSION}"
          git push

      - name: Install GitHub CLI
        run: brew install gh

      - name: Create GitHub Release and Upload Assets
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          TAG=${{ github.event.inputs.tag || github.ref_name }}

          gh release create "$TAG" ./airdrop ./airdrop_darwin_universal.tar.gz \
            --title "Release $TAG" \
            --notes "Automated release for version $TAG"
